[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
actix-web = "4.3.1"
tracing-actix-web = "0.7.5"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.181", features = ["derive"] }
config = "0.13.3"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.8"
tracing-log = "0.1.3"
secrecy = { version = "0.8.0", features = ["serde"] }
serde-aux = "4"
unicode-segmentation = "1.10.1"
validator = "0.16"
reqwest = { version = "0.11.18", default_features = false, features = ["json", "rustls-tls"] }
rand = { version = "0.8.5", features = ["std_rng"] }
thiserror = "1.0.44"
anyhow = "1.0.72"

[dependencies.sqlx]
version = "0.7.1"
default-features = false
features = ["macros", "postgres", "uuid", "chrono", "migrate", "runtime-tokio-rustls"]


[dev-dependencies]
once_cell = "1.18.0"
claims = { version = "0.7" }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
fake = "2.6.1"
rand = "0.8.5"
tokio = { version = "1.29.1", features = ["macros", "rt"] }
wiremock = "0.5.19"
serde_json = "1"
linkify = "0.10.0"
