redis_uri = "redis://127.0.0.1:6379"

[application]
hmac_secret = "long-and-very-secret-random-key-needed-to-veryfy-message-integrity"
port = 8078

[database]
database_name = "newsletter"
host = "localhost"
password = "password"
port = 5432
username = "postgres"

[email_client]
authorization_token = "dev-secret-token"
base_url = "localhost"
sender_email = "test@gmail.com"
timeout_milliseconds = 5000
